# -*- coding: utf-8 -*-
"""Tutorial 3 - Florestas aleatórias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SdSZQY1L6EJyRl5i9YSRqemdqhAJVnm8
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

digits = load_digits()

dir(digits)

plt.gray()
for i in range(4):
  plt.matshow(digits.images[i])

df = pd.DataFrame(digits.data)
df

df['target'] = digits.target
df

len(digits.data)

x_train, x_test, y_train, y_test = train_test_split(df.drop(['target'], axis='columns'), digits.target, test_size=0.2) #20% do nosso dataset

len(x_train)

len(x_test)

model = RandomForestClassifier()

model.verbose = 1

model.fit(x_train, y_train)

model.score(x_test, y_test)

y_predicted= model.predict(x_test)

confusion = confusion_matrix(y_test, y_predicted)

confusion

plt.figure(figsize=(10,7))
sn.heatmap(confusion, annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth')